CREATE TABLE `data_platform_bus_line_header_data`
(
  `BusLine`                              int(16) NOT NULL,
  `BusLineType`                          varchar(4) NOT NULL,
  `BusLineOwner`                         int(12) NOT NULL,
  `BusLineOwnerBusinessPartnerRole`      varchar(40) NOT NULL,
  `Brand`                                int(16) NOT NULL,
  `PersonResponsible`                    varchar(40) DEFAULT NULL,
  `URL`                                  varchar(200) DEFAULT NULL,
  `ValidityStartDate`                    date NOT NULL,
  `ValidityEndDate`                      date NOT NULL,
  `DepartureBusStopOfOutboundLine`       int(16) NOT NULL,
  `DestinationBusStopOfOutboundLine`     int(16) NOT NULL,
  `Description`                          varchar(60) NOT NULL,
  `LongText`                             varchar(1000) NOT NULL,
  `Introduction`                         varchar(200) DEFAULT NULL,
  `Project`                              int(16) DEFAULT NULL,
  `WBSElement`                           int(8) DEFAULT NULL,
  `Tag1`                                 varchar(40) DEFAULT NULL,
  `Tag2`                                 varchar(40) DEFAULT NULL,
  `Tag3`                                 varchar(40) DEFAULT NULL,
  `Tag4`                                 varchar(40) DEFAULT NULL,
  `CreationDate`                         date NOT NULL,
  `CreationTime`                         time NOT NULL,
  `LastChangeDate`                       date NOT NULL,
  `LastChangeTime`                       time NOT NULL,
  `CreateUser`                           int(12) NOT NULL,
  `LastChangeUser`                       int(12) NOT NULL,
  `IsReleased`                           tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`                  tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`BusLine`),

    CONSTRAINT `DPFMBusLineHeaderDataBusLineType_fk` FOREIGN KEY (`BusLineType`) REFERENCES `data_platform_bus_line_type_bus_line_type_data` (`BusLineType`),
    CONSTRAINT `DPFMBusLineHeaderDataBusLineOwner_fk` FOREIGN KEY (`BusLineOwner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMBusLineHeaderDataBusLineOwnerBPRole_fk` FOREIGN KEY (`BusLineOwnerBusinessPartnerRole`) REFERENCES `data_platform_bp_role_bp_role_data` (`BusinessPartnerRole`),
    CONSTRAINT `DPFMBusLineHeaderDataBrand_fk` FOREIGN KEY (`Brand`) REFERENCES `data_platform_brand_header_data` (`Brand`),
    CONSTRAINT `DPFMBusLineHeaderDataDptBusStopOfOBLine_fk` FOREIGN KEY (`DepartureBusStopOfOutboundLine`) REFERENCES `data_platform_bus_stop_header_data` (`BusStop`),
    CONSTRAINT `DPFMBusLineHeaderDataDstBusStopOfOBLine_fk` FOREIGN KEY (`DestinationBusStopOfOutboundLine`) REFERENCES `data_platform_bus_stop_header_data` (`BusStop`),
    CONSTRAINT `DPFMBusLineHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMBusLineHeaderDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMBusLineHeaderDataCreateUser_fk` FOREIGN KEY (`CreateUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMBusLineHeaderDataLastChangeUser_fk` FOREIGN KEY (`LastChangeUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
